#!/bin/bash
#!/bin/sh
#Created By MAJESTAR	
if [ "$EUID" -ne 0 ] 
  then 
  clear
 echo -e "\033[32;5m
 Lütfen Asistanı Sudo Kullanıcı olarak çalıştırın \033[0m"
  sleep 1
 echo -e "\033[1;31m' Şunu Yazın  : sudo Asistan \033[4;34m"
  exit
 # Programın düzgün çalışabilmesi için sudo yetkisi alması lazım bu yüzden normal bir şekilde çalıştırılır ise uyarı vermek için böyle bir kod yazdım
fi 
clear
banner(){	
echo""
figlet -c -f Bloody "Terminal Asistan" | /usr/games/lolcat         
echo -e '\033[0;94m -=[  Terminal Asistanım  ]=-
 -=[Created By MAJESTAR]=- 
 '
echo -e '
\e[31m[1]\e[32m Linux Menüsü 	                        \e[31m[3]\e[32m Dosya İşlemleri Menüsü
\e[31m[2]\e[32m Müzik & Video İndirme Menüsü	        \e[31m[4]\e[32m Eğlenceli Menü  
\e[31m[5]\e[32m Terminal Asistanı Sİl 

                                     
                                  \e[31m[0]Çıkış
'
read -p  "İşlem Numarası: " islem
}

banner


if [[ $islem == 1 || $islem == 01 ]]; then
   
    clear
    sudo bash /bin/Terminal-Asistan/menuler/lm.sh

elif [[ $islem == 2 || $islem == 02 ]]; then
	clear
	bash /bin/Terminal-Asistan/menuler/mv.sh
	

elif [[ $islem == 3 || $islem == 03 ]]; then
	sudo bash /bin/Terminal-Asistan/menuler/di.sh
elif [[ $islem == 4 || $islem == 04 ]]; then
	sudo bash /bin/Terminal-Asistan/menuler/em.sh

elif [[ $islem == 5 || $islem == 05 ]]; then
read -p "ASİSTANI SİLMEK İSTEDİĞİNİZE EMİNMİSİNİZ ? E/H : " sil
if [[ $sil == "e" || $sil == "E" ]]; then
echo "Siliniyor.."
sleep 2
sudo rm -rf /bin/Terminal-Asistan
sudo rm /bin/Asistan
echo "Asistan Sisteminizden Silindi "
elif [[ $sil == "H" || $sil == "h" ]]; then
sudo bash Asistan
fi
elif [[ $islem == 00 ]]; then
	echo "GÖRÜŞMEK ÜZERE :))))) "
	exit 1
else
	echo -e '\033[36;40;1m Girdiğniz İşlem Numarasını Kontrol Ediniz....'	
	sleep 1
	clear 
	sudo bash Asistan
# Burada bir işlem seçmesini istedim ve seçtiği işleme göre istediği menüye yönlendirme işlemi yaptım 
# VE eğer hatalı bir numara vs girer ise tekrardan programı çalıştırma komutu verdim 
fi
#Created By MAJESTAR